### ISSUE TITLE
CLI Version?

### ISSUE THREAD

**Issue by nxion** [musicmancorley/BriarIDS#13]
Hi there!

First of all, this is awesome. I have been looking for something like this for a long time and working on getting it setup as I type. I do have a question but I just may have missed it and if so my apologies. Is there a way to run this w/o a GUI or is the only way to install everything is with the PyQT app?

**Comment by g3tsyst3m** [comment]
no apology necessary nxion.  I probably should add this into the WIKI now that you mention it.
Yes, there is a CLI installer for both Bro and Suricata. once you clone BriarIDS, just run the following scripts below.  they are in the /scripts folder: 
bromenu.sh and choose 1. Install Bro for installing bro

suricata-install-script.sh is the script for installing Suricata

hope that helps
-Robbie

**Comment by nxion** [comment]
It does indeed, thank you. I think I will put a GUI on it anyway so I can mess with the other features <s>I also just realized that the pi doesn't have a gui but your just forwarding everything over ssh so that was my mistake.</s> Also do you really only use one NIC and if you wanted to, could this setup be used with two? For example a usb wifi for management and the onboard NIC for monitor?

**Comment by g3tsyst3m** [comment]
you are welcome @nxion 

I use one NIC when the tomato router is my primary routing device.  If a hardware TAP device is incorporated into the project, you would then want to use one NIC for management and the other for sniffing.  you are correct

Also, here is our BriarIDS discussion forum in case you are interested: https://groups.google.com/forum/#!forum/briarids

all the best
-Robbie

**Comment by nxion** [comment]
perfect. thank you!
