### ISSUE TITLE
bro install fails

### ISSUE THREAD

**Issue by g3tsyst3m** [musicmancorley/BriarIDS#14]
bro install fails on the latest raspian distribution with all patches.

To get arround the compile problems you have to manually install the libssl1.0-dev package before starting the install process
I will correct this soon.  thanks
-Robbie

**Comment by HollywoodMarks** [comment]
I am still seeing this issue.  I tried to manually install the package above, however, it gets removed and libssl-dev is installed, then the install fails.

**Comment by g3tsyst3m** [comment]
sorry to hear that @HollywoodMarks .  try it now.  I made an update in the bro install script to account for Debian based OS installs

**Comment by HollywoodMarks** [comment]
Thank you.  I was able to get it working by breaking the install of packages including libssl-dev, and manually installing libssl1.0-dev as you stated earlier.

**Comment by g3tsyst3m** [comment]
glad to hear it cooperated for you @HollywoodMarks
