### ISSUE TITLE
Alive ?

### ISSUE THREAD

**Issue by Mikiya83** [musicmancorley/BriarIDS#17]
Hi ! 
I search a simple way to convert a Pi to IDS for home network. Your project seems cool ! But is it still alive/updated ? It's not a reproach, i just want to install a maintained IDS, thanks for your project anyway !

**Comment by g3tsyst3m** [comment]
hi @Mikiya83 .  sadly I have not been able to continue providing updates for this project.  It was a lot of fun to put together and I'd love to integrate kibana and elastic stack into it some day.  for now, the main item of importance would be updating the dependencies and suricata/bro versions as I'd say they are far behind
