### ISSUE TITLE
Menu Broken

### ISSUE THREAD

**Issue by ahmadihamid** [musicmancorley/BriarIDS#2]
menu break when opened directly from desktop (over ssh working fine)
here is the error : 
`pi@raspberrypi:~/BriarIDS $ sudo python BriarIDS.py 
loading main menu...
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    129 (MIT-SHM)
    Minor opcode: 1 (X_ShmAttach)
      Resource id:  0x2c00001
      X Error: BadShmSeg (invalid shared segment parameter) 128
        Extension:    129 (MIT-SHM)
          Minor opcode: 5 (X_ShmCreatePixmap)
            Resource id:  0x2c0000d
            X Error: BadDrawable (invalid Pixmap or Window parameter) 9
              Major opcode: 62 (X_CopyArea)
                Resource id:  0x2c0000e
                X Error: BadDrawable (invalid Pixmap or Window parameter) 9
                  Major opcode: 62 (X_CopyArea)
                    Resource id:  0x2c0000e
                    X Error: BadDrawable (invalid Pixmap or Window parameter) 9
.....
`

**Comment by g3tsyst3m** [comment]
Are you by chance using VNC to manage your Desktop environment?  Or plugged into an external monitor via an HDMI cable?
thanks
-Robbie

**Comment by ahmadihamid** [comment]
yes, I'm using VNC 
so that's the problem?

**Comment by g3tsyst3m** [comment]
Hey @ahmadihamid. It's not VNC that's the problem but rather pyQT and the X-server.  

try starting vnc with elevated privileges, like so: **sudo tightvncserver**

let me know if this works for you

**Comment by g3tsyst3m** [comment]
Due to inactivity, this issue will be deemed as resolved.  If the issue persists, please do open another issue request with further information surrounding your issue.  thanks!
