### ISSUE TITLE
OpenWRT instead of Tomato?

### ISSUE THREAD

**Issue by S1llyB01** [musicmancorley/BriarIDS#3]
No really an issue, but thought to ask here; Will BriarIDS setup work if I replace a tomato-supported router with an OpenWRT one?

From what I see all you'd need is IPTABLES, and as far as I know OpenWRT supports it as well.

Thanks!

**Comment by g3tsyst3m** [comment]
Hey there @arieljt 
I would think OpenWRT should work just fine.  I have not tested it personally, but there are good resources on the web documenting IPTABLES use cases with OpenWRT.  Here's a link that should help get you started on the right path with OpenWRT: http://www.ayomaonline.com/security/analyzing-network-traffic-with-openwrt/
~Robbie
