### ISSUE TITLE
/opt/nsm/bro is empty after install

### ISSUE THREAD

**Issue by glyph02** [musicmancorley/BriarIDS#4]
After clicking the "Install Bro-2.5 and Intel Feed Agent" button, it leaves me with a prompt saying 

```
Almost done.  What you will want to do now is to add some feeds.  Since the raspberry pi is limited in its processing power, signing up for too many feeds will overload the unit.
I would suggest signing up for just a few feeds initially, such as 'Phish Tank Intel Feed' and 'Known Tor exit nodes'.
Once you have added your feeds to your sensor, go ahead and pull that info into Bro by issuing the following command:
sudo -u critical-stack critical-stack-intel pull
Now, you will want to perform three final changes.  Go to /opt/nsm/bro/etc
edit Networks.cfg and be sure to add something similar to the following:
10.0.0.0/8          Private IP space
192.168.0.0/16      Private IP space
pubicipgoeshere/32      Public WAN IP space
Now, edit nodes.cfg and add in your interface, either eth0 or eth1, etc
finally, start bro.  go to /nsm/opt/bro/bin/ as ROOT and do: ./broctl
type in 'deploy' which should auto start the application.  Log files will be in /nsm/opt/bro/logs/current for active scans and folder archives for completed scans.
That's it. Congrats!
```

However, /opt/nsm/bro is empty.  There are 3 files in /root/bro-2.5.tar.gz.[123], but I couldn't find hide nor hair of bro elsewhere on the system.

**Comment by g3tsyst3m** [comment]
sounds like it could be a dependency issue without having any logs to work off of.  Have you made it beyond the configure command?  Also pay attention to your make command output in the terminal console to see if any errors were presented during install.  I made a quick edit on the bro-installer.sh file to remove the 'clear' command so you can review the command output and see if there were any errors during the 'make' and 'make install' command.  just click 'Check for Updates from Github' on the Briar main menu to get the update.  Below is what you should expect to see after the configure command:
====================|  Bro Build Summary  |=====================

Install prefix:    /opt/nsm/bro
Bro Script Path:   /opt/nsm/bro/share/bro
Debug mode:        false

CC:                /usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -std=c++11 -O2 -g -DNDEBUG
CPP:               /usr/bin/c++

Broker:            false
Broker Python:     false
Broccoli:          true
Broctl:            true
Aux. Tools:        true

GeoIP:             true
gperftools found:  false
        tcmalloc:  false
       debugging:  false
jemalloc:          false

================================================================

-- Configuring done
-- Generating done
-- Build files have been written to: /root/bro-2.5/build
issuing 'make' command.

**Comment by glyph02** [comment]
Thanks - it was compiling, but I'd always missed the output before the clear, so this change should at least reveal what's happening.

I've kicked it off and will check on it tomorrow.

**Comment by glyph02** [comment]
All good.  I did switch from a Raspberry Pi B to a Raspberry Pi 3 B - I'm guessing that made the difference.  I'll switch back to the slower platform and confirm.

**Comment by g3tsyst3m** [comment]
Glad it cooperated for you on the Pi 3 B.  I'll be sure to update the wiki on confirmed supported Pi models.  If you find out what went wrong on the older Pi unit I'll see if I can add a legacy install option to the script to support older units depending on what the problem is.  Thanks @glyph02

**Comment by glyph02** [comment]
Did you change anything else other than the pause?   It successfully compiled and installed on the older platform as well.  (shrug)

**Comment by g3tsyst3m** [comment]
Hey @glyph02, nope no changes/commits were made that I can recall other than those simple edits made to the clear/pause command.  Maybe it caught a dependency that was missed the first time around or something.  I wouldn't beat yourself up over it.  These things happen.  I'm just glad it is cooperating for you now.  here's the commits section if you ever want to check out the specific changes made on a given day/month: https://github.com/musicmancorley/BriarIDS/commits/master

**Comment by glyph02** [comment]
Glad it's solved.  Cheers!
