### ISSUE TITLE
Does this need a tomato router?

### ISSUE THREAD

**Issue by wkleinhenz** [musicmancorley/BriarIDS#5]
Could this be configured to be running using switch port mirroring on a switch or in-line with multiple interfaces

**Comment by g3tsyst3m** [comment]
@wkleinhenz yes by all means switch port mirroring would be the ideal option, inline too.  The tomato router is simply meant to serve as the cheaper option for the copying of packets to the monitor interface with the supported --tee command.

**Comment by wkleinhenz** [comment]
Alright, that clears that up, thanks for the help.

**Comment by g3tsyst3m** [comment]
Glad to help
