### ISSUE TITLE
Documentation change/question

### ISSUE THREAD

**Issue by mauvehed** [musicmancorley/BriarIDS#8]
From https://github.com/musicmancorley/BriarIDS/wiki/Installation

1. Clone the repo! git clone https://github.com/musicmancorley/BriarIDS.git
2. Next, ssh into your PI: ssh -X pi@your_pi_ip
3. Needs to be run using sudo: sudo python BriarIDS.py

Shouldn't you SSH in to the PI first and then clone the repo second? Otherwise you're just cloning it to your local machine and then expecting it to also show up on the PI when you execute step 3.

**Comment by g3tsyst3m** [comment]
good catch @mauvehed 
I'll make the changes now.  thx
